// API key loaded from environment variable (.env.local)
// To use: create .env.local with VITE_GEMINI_API_KEY=your_key_here
const apiKey = import.meta.env.VITE_GEMINI_API_KEY || "";

const MOCK_RESPONSES = [
    "Entropy is just information hiding in the shadows.",
    "The waveform has collapsed into a singular moment of clarity.",
    "Your query resonates with the frequencies of the universe.",
    "Quantum entanglement suggests we are all connected.",
    "Observing the code changes its outcome.",
    "In a superposition of 'working' and 'debugging'.",
    "Reality is a persistent illusion generated by code."
];

export const callGemini = async (prompt, systemInstruction = "") => {
    // Jika tidak ada API Key, gunakan Mock Response (Simulasi)
    if (!apiKey) {
        console.warn("Gemini API Key missing. Using mock response.");
        await new Promise(resolve => setTimeout(resolve, 1500)); // Simulasi delay network
        return MOCK_RESPONSES[Math.floor(Math.random() * MOCK_RESPONSES.length)];
    }

    try {
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`,
            {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    systemInstruction: { parts: [{ text: systemInstruction }] },
                }),
            }
        );
        if (!response.ok) throw new Error("API Error");
        const data = await response.json();
        return data.candidates?.[0]?.content?.parts?.[0]?.text || "Fluktuasi kuantum mengganggu sinyal.";
    } catch (error) {
        console.error("Gemini Error:", error);
        return "Koneksi ke medan kuantum terputus.";
    }
};
